modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="disney"
version="1.0.0"
displayName="Disney"
displayURL="https://mcreator.net"
credits="Certaines textures et models proviennent du serveur Minecraft MineDisney : https://www.minedisney.com"
authors="Lou"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.disney]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration